#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSqlDemo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LPU_Db")]
	public partial class LpuDbClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertStudentInfo(StudentInfo instance);
    partial void UpdateStudentInfo(StudentInfo instance);
    partial void DeleteStudentInfo(StudentInfo instance);
    #endregion
		
		public LpuDbClassesDataContext() : 
				base(global::LinqToSqlDemo.Properties.Settings.Default.LPU_DbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LpuDbClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LpuDbClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LpuDbClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LpuDbClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Person> Persons
		{
			get
			{
				return this.GetTable<Person>();
			}
		}
		
		public System.Data.Linq.Table<StudentMark> StudentMarks
		{
			get
			{
				return this.GetTable<StudentMark>();
			}
		}
		
		public System.Data.Linq.Table<StudentInfo> StudentInfos
		{
			get
			{
				return this.GetTable<StudentInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Person")]
	public partial class Person
	{
		
		private System.Nullable<int> _Id;
		
		private string _Name;
		
		private System.Nullable<int> _Age;
		
		private string _Address;
		
		private string _PhoneNumber;
		
		private string _SocialStatus;
		
		public Person()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int")]
		public System.Nullable<int> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="VarChar(10)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this._PhoneNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SocialStatus", DbType="VarChar(10)")]
		public string SocialStatus
		{
			get
			{
				return this._SocialStatus;
			}
			set
			{
				if ((this._SocialStatus != value))
				{
					this._SocialStatus = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudentMarks")]
	public partial class StudentMark
	{
		
		private int _srNo;
		
		private System.Nullable<int> _RollNo;
		
		private int _Phy;
		
		private int _Chem;
		
		private int _Maths;
		
		private System.Nullable<int> _Total;
		
		private System.Nullable<int> _Perc;
		
		public StudentMark()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_srNo", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int srNo
		{
			get
			{
				return this._srNo;
			}
			set
			{
				if ((this._srNo != value))
				{
					this._srNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RollNo", DbType="Int")]
		public System.Nullable<int> RollNo
		{
			get
			{
				return this._RollNo;
			}
			set
			{
				if ((this._RollNo != value))
				{
					this._RollNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phy", DbType="Int NOT NULL")]
		public int Phy
		{
			get
			{
				return this._Phy;
			}
			set
			{
				if ((this._Phy != value))
				{
					this._Phy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chem", DbType="Int NOT NULL")]
		public int Chem
		{
			get
			{
				return this._Chem;
			}
			set
			{
				if ((this._Chem != value))
				{
					this._Chem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maths", DbType="Int NOT NULL")]
		public int Maths
		{
			get
			{
				return this._Maths;
			}
			set
			{
				if ((this._Maths != value))
				{
					this._Maths = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Perc", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Perc
		{
			get
			{
				return this._Perc;
			}
			set
			{
				if ((this._Perc != value))
				{
					this._Perc = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudentInfo")]
	public partial class StudentInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RollNo;
		
		private string _Name;
		
		private System.Nullable<short> _Age;
		
		private string _LocalAddr;
		
		private string _PerAddress;
		
		private string _PhoneNo;
		
		private string _SchoolName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRollNoChanging(int value);
    partial void OnRollNoChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAgeChanging(System.Nullable<short> value);
    partial void OnAgeChanged();
    partial void OnLocalAddrChanging(string value);
    partial void OnLocalAddrChanged();
    partial void OnPerAddressChanging(string value);
    partial void OnPerAddressChanged();
    partial void OnPhoneNoChanging(string value);
    partial void OnPhoneNoChanged();
    partial void OnSchoolNameChanging(string value);
    partial void OnSchoolNameChanged();
    #endregion
		
		public StudentInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RollNo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int RollNo
		{
			get
			{
				return this._RollNo;
			}
			set
			{
				if ((this._RollNo != value))
				{
					this.OnRollNoChanging(value);
					this.SendPropertyChanging();
					this._RollNo = value;
					this.SendPropertyChanged("RollNo");
					this.OnRollNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="SmallInt")]
		public System.Nullable<short> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocalAddr", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LocalAddr
		{
			get
			{
				return this._LocalAddr;
			}
			set
			{
				if ((this._LocalAddr != value))
				{
					this.OnLocalAddrChanging(value);
					this.SendPropertyChanging();
					this._LocalAddr = value;
					this.SendPropertyChanged("LocalAddr");
					this.OnLocalAddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerAddress", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PerAddress
		{
			get
			{
				return this._PerAddress;
			}
			set
			{
				if ((this._PerAddress != value))
				{
					this.OnPerAddressChanging(value);
					this.SendPropertyChanging();
					this._PerAddress = value;
					this.SendPropertyChanged("PerAddress");
					this.OnPerAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNo", DbType="VarChar(10)")]
		public string PhoneNo
		{
			get
			{
				return this._PhoneNo;
			}
			set
			{
				if ((this._PhoneNo != value))
				{
					this.OnPhoneNoChanging(value);
					this.SendPropertyChanging();
					this._PhoneNo = value;
					this.SendPropertyChanged("PhoneNo");
					this.OnPhoneNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SchoolName", DbType="VarChar(10)")]
		public string SchoolName
		{
			get
			{
				return this._SchoolName;
			}
			set
			{
				if ((this._SchoolName != value))
				{
					this.OnSchoolNameChanging(value);
					this.SendPropertyChanging();
					this._SchoolName = value;
					this.SendPropertyChanged("SchoolName");
					this.OnSchoolNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
